### ISSUE TITLE
Broken on coder-server

### ISSUE THREAD

**Issue by yorrd** [hangxingliu/vscode-coding-tracker-server#18]
Hi man, it's us again. We just tried installing the extension on our coder.com instance and it doesn't work (says command not found). Is there anything we are doing wrong? If you want access to the instance to test it, let me know, I can set up one for you to check it out on :)

Greetings!

**Comment by hangxingliu** [comment]
I will have a look later. Because it may be caused by the construction of coder.com is different from pure VSCode.

**Comment by hangxingliu** [comment]
You are using an online server provided by coder.com or self-hosting? @yorrd

**Comment by yorrd** [comment]
@hangxingliu we're self hosting

**Comment by yorrd** [comment]
@hangxingliu can we help you in any way here? if you need access to a coder instance, I can give you the password of an instance that runs in a sandbox for you to play around with if that helps at all.

**Comment by hangxingliu** [comment]
@yorrd Sorry for replying late. And you can send the information to my email. I can diagnose it after tomorrow night (Because I need to finish my work firstly, LOL)

**Comment by yorrd** [comment]
Just to reiterate for everyone wondering as well: for the time being, you can call `npm install` in `~/coder-config/extensions/<this extension>/` and it will work again
