### ISSUE TITLE
Change time format in some graphs

### ISSUE THREAD

**Issue by caioflores** [hangxingliu/vscode-coding-tracker-server#3]
Some graphs show time in decimal hours format (1.5h, 0.25h). It would be better a format like 1h 30m or something like that.

**Comment by hangxingliu** [comment]
Thanks for your proposal. It is a good idea to improving readable in report page.

I am busy recent days for a commercial project. So I will finish this function and release new version in August (include other optimizations)

And it will be better if you can add by yourself then give this repository a pull request. your can refer [TODO.md](https://github.com/hangxingliu/vscode-coding-tracker-server/blob/master/TODO.md)

---

Thanks

**Comment by caioflores** [comment]
ok @hangxingliu, I'm working on it! I never worked with Typescript so some feedback on my code would be nice. And I never worked on a opensource project haha.
Well I forked the repo and I'll make a pr soon.

**Comment by hangxingliu** [comment]
Ok. Thanks for your contributing. And if you meet some trouble or something non understand, you can email to me or comment in here.

(There only has little comments in this server side codes . Because I coded these server side codes eagerly for getting my coding report charts. haha)

My email: <hangxingliu@gmail.com>

**Comment by caioflores** [comment]
@hangxingliu I made a pr for this issue.
I had some trouble to find a way to change the time format in max/average markpoints in the graphs, any help on it?

**Comment by hangxingliu** [comment]
In this project, I used chart library is echarts (It is amazing and easy)
You can refer this page about markPoints: <https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.markPoint.data.value>
In my code, I wrap most option of echarts in file: `frontend/src/js/echartsUtils.js`

P.s. If you meet some trouble around charts style or behavior. you can refer echarts document (It has quickly search function ): <https://ecomfe.github.io/echarts-doc/public/en/tutorial.html>

And if you want to continuously edit this project , you can follow branch `0.5.0-develop`. I will continuously add comments and functions after finish my daily job everyday

**Comment by caioflores** [comment]
@hangxingliu thanks for the tips, I'll continue contributing when I can. I'll follow the branch.

**Comment by hangxingliu** [comment]
Fix <https://github.com/hangxingliu/vscode-coding-tracker-server/commit/684bbf886ad05ee74471863346e070393053c236>
