### ISSUE TITLE
Time spent in branches/commits chart

### ISSUE THREAD

**Issue by caioflores** [hangxingliu/vscode-coding-tracker-server#8]
A chart to show how much time was spent in each branch worked.
Maybe in each commit too? We can sum time time spent in each file that was included in the commit or something like that.

**Comment by hangxingliu** [comment]
Actually, I added this idea into TODO.md in extension side repository.
<https://github.com/hangxingliu/vscode-coding-tracker/blob/master/TODO.md>

And I need to reference other extension and document  before adding it into repository.

Thanks for your proposal.

**Comment by hangxingliu** [comment]
Added in dc33cbfb7f803a9e33e0e97fd0f2faab41ba22a0
It will be released in next version
